// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ8nQVGLqoKY_TMWmf3HVIbV7UFDfjb8Y',
    appId: '1:546303432184:web:03ed60b1a8e498c256b20d',
    messagingSenderId: '546303432184',
    projectId: 'dating-app-3878b',
    authDomain: 'dating-app-3878b.firebaseapp.com',
    storageBucket: 'dating-app-3878b.appspot.com',
    measurementId: 'G-TK309VYV8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-5cbmfB-mkOwub3pMl8a4IiLyCMvuKt0',
    appId: '1:546303432184:android:549ecfa598e6ac6b56b20d',
    messagingSenderId: '546303432184',
    projectId: 'dating-app-3878b',
    storageBucket: 'dating-app-3878b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaRwBsWeKqjj_AXnXR1q2U5L7VvevJiyw',
    appId: '1:546303432184:ios:c7275c83b4e00f3a56b20d',
    messagingSenderId: '546303432184',
    projectId: 'dating-app-3878b',
    storageBucket: 'dating-app-3878b.appspot.com',
    iosBundleId: 'com.example.matrimonyApp',
  );
}
